from .View import View
from .AlunosView import AlunosView
from .MatriculaView import MatriculaView
from .PlanosView import PlanosView
from .PagamentoView import PagamentoView
from .TreinoAlunoView import TreinoAlunoView
from .TreinoView import TreinoView
from .MedicaoView import MedicaoView
from .MedidaView import MedidaView
from .PartCorpoView import PartCorpoView
from .MusculoView import MusculoView